### ISSUE TITLE
Anchor data on chain

### ISSUE THREAD

**Issue by paul121** [cambiumteam/pinning_service#7]
After the pinning service receives & processes data #8 it needs to anchor the data on chain.

Anchor data on chain:
1. For now, just call the `regen` cli from python. In the future consider using protobuf to build & broadcast these txs directly in python?
2. Send MsgAnchor: https://buf.build/regen/regen-ledger/docs/main:regen.data.v1#regen.data.v1.MsgAnchor

**Comment by wgardiner** [comment]
for development workflow we can set up a docker compose file to run a localnet
https://github.com/ovrclk/cosmos-omnibus/tree/master/regen
https://github.com/regen-network/regen-ledger/blob/master/Makefile#L385-L408

**Comment by wgardiner** [comment]
from session on 5/4
- created account in local test keyring 
```
regen keys add pinning-service-test --keyring-backend test --keyring-dir ./docker/.testnets/keys
```

- import node0 key to keyring
```
regen keys add node0 --recover --keyring-backend test --keyring-dir ./docker/.testnets/keys/
```

- send tokens from node0 to pinning-service-test
```
regen tx bank send regen1qmlfrl880zjkvequ642pygkwuzr487ve99g8ze regen1l30aw2w8ghqaxcx3kesgvy9vecurp7pgj6rdne 1000testtoken --keyring-backend test --keyring-dir ./docker/.testnets/keys/ --chain-id chain-YsT5fv --node http://localhost:26657 --gas auto --fees 2stake

regen tx bank send regen1qmlfrl880zjkvequ642pygkwuzr487ve99g8ze regen1l30aw2w8ghqaxcx3kesgvy9vecurp7pgj6rdne 500stake --keyring-backend test --keyring-dir ./docker/.testnets/keys/ --chain-id chain-YsT5fv --node http://localhost:26657 --gas auto --fees 2stake
```

- define resolver
```
docker run --rm --network host \
    -v $(pwd)/docker/.testnets/keys:/regen-keys ghcr.io/cambiumteam/pinning_service:regen-test \
    regen tx data define-resolver http://localhost:8000/resource --from pinning-service-test -y \
    --keyring-backend test --keyring-dir /regen-keys/ \
    --chain-id chain-YsT5fv --node http://localhost:26657 \
    --gas auto --fees 2stake
```
